version: '3.7'

services:
  dev:
    build:
      context: ../../
      dockerfile: docker/lfz/Dockerfile
    container_name: dev
    stdin_open: true
    tty: true
    hostname: localhost
    ports:
      - 80:80
      - 443:443
      - 3000:3000
      - 3001:3001
    volumes:
      - lfz_dev_home:/home/dev
      - lfz_dev_data:/var/lib/mysql/
      - ../../../../:/home/dev/Desktop
    command: ["tail", "-f", "/dev/null"]

volumes:
  lfz_dev_data:
  lfz_dev_home:
